# Basic PyTorch Operations

## Initialisation and Basic Settings

In [2]:
import torch

In [4]:
my_tensor = torch.tensor([[1,2,3,],[4,5,6]] ,dtype = torch.float32, device = 'cuda')

In [5]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor([[1,2,3] , [4,5,6]], dtype = torch.float32, device = device, requires_grad = True)

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [5]:
print(my_tensor.dtype)

torch.float32


In [6]:
print(my_tensor.device)

cuda:0


In [7]:
print(my_tensor.shape)

torch.Size([2, 3])


In [8]:
print(my_tensor.requires_grad)

True


## Other Initialisation Methods

### Initialisation by Zeros

In [9]:
x = torch.empty(size = (3,3))

print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
x = torch.zeros((3,3))

print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Random Initialisation

In [11]:
x = torch.rand(3,3)

print(x)

tensor([[0.9008, 0.9609, 0.9372],
        [0.2041, 0.4007, 0.8859],
        [0.8428, 0.2221, 0.1278]])


### Ones Initialisation

In [12]:
x = torch.ones(3,3)

print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### Identity Matrix Creation

In [13]:
x = torch.eye(5,5)

print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


### Range Initialisation

In [14]:
x = torch.arange(start=0,end=5,step=1)

print(x)

tensor([0, 1, 2, 3, 4])


In [3]:
x = torch.linspace(start=0.1,end=1,steps=10)

print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


### Distribution Initialisation

In [4]:
x = torch.empty(size=(1,5)).normal_(mean=0,std=1)

print(x)

tensor([[ 0.0506, -1.1894, -0.4582,  1.3848, -2.2305]])


In [5]:
x = torch.empty(size=(1,5)).uniform_(0,1)

print(x)

tensor([[0.2842, 0.0671, 0.2801, 0.3806, 0.5825]])


## Convert to other types

In [9]:
tensor=torch.arange(0,5)

### Boolean True/False

In [10]:
print(tensor.bool())

tensor([False,  True,  True,  True,  True])


### int16

In [11]:
print(tensor.short())

tensor([0, 1, 2, 3, 4], dtype=torch.int16)


### int64

In [12]:
print(tensor.long())

tensor([0, 1, 2, 3, 4])


### float16

In [13]:
print(tensor.half())

tensor([0., 1., 2., 3., 4.], dtype=torch.float16)


### float32

In [14]:
print(tensor.float())

tensor([0., 1., 2., 3., 4.])


### float64

In [15]:
print(tensor.double())

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)


## Array to Tensor Conversion

In [21]:
import numpy as np

np_array = np.zeros((5,5))

tensor = torch.from_numpy(np_array)

back_to_numpy = tensor.numpy()

print(tensor)

print(back_to_numpy)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
